version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.9.0
    - 1.9.1
  - dependency-name: loofah
    versions:
    - 2.9.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: publiclab-editor
    versions:
    - 3.0.1
    - 3.0.2
  - dependency-name: jquery
    versions:
    - 3.5.1
